mode: rule
allow-lan: true
unified-delay: true
bind-address: '*'
log-level: silent
ipv6: false
geodata-mode: true
external-controller: 0.0.0.0:9090
external-ui: clash-dashboard/dist
tcp-concurrent: true
interface-name: ""
enable-process: true
geodata-loader: memconservative
secret: ""
sniffer:
  enable: false
  sniffing:
    - tls
    - http
  force-domain:
    - '+'
  skip-domain:
    - 'google.com'
  port-whitelist:
    - 80
    - 443
    - 8000-9000
profile:
  store-selected: true
  store-fake-ip: false
dns:
  enable: true
  device: Meta
  ipv6: false
  default-nameserver: 
    - 8.8.8.8
    - 1.1.1.1
  listen: 0.0.0.0:1053
  use-hosts: true
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter: ['networktest.twilio.com', '+.twilio.com']
  nameserver:
    - 1.0.0.1
    # ISI IP BUG YANG KALIAN GUNAKAN 
  proxy-server-nameserver:
    - 1.0.0.1
    # ISI IP BUG YANG KALIAN GUNAKAN 
  fallback: []
  fallback-filter:
    geoip: false
    geoip-code: 'ID'
    geosite:
      - GFW
      - GREATFIRE
    domain: ['google.com']
    ipcidr: [240.0.0.0/4]
tun:
  enable: false
  device: Meta
  stack: gvisor
  dns-hijack:
    - 'any:53'
    - 'tcp://any:53'
  auto-route: true
  auto-detect-interface: true
iptables: {enable: false, inbound-interface: "", bypass: []}
hosts:
  'note.microsoft.com': 104.18.38.174
  'maps.google.com': 104.18.10.39
geox-url:
  mmdb: "https://cdn.jsdelivr.net/gh/Dreamacro/maxmind-geoip@release/Country.mmdb"
  geoip: "https://github.com/v2fly/geoip/raw/release/geoip-only-cn-private.dat"
  geosite: "https://github.com/Loyalsoldier/v2ray-rules-dat/raw/release/geosite.dat"
tproxy-port: 9898
proxies:
  - name: Sanggoro
    server: www.udemy.com
    port: 443
    type: vmess
    uuid: 5ee99a60-be72-11ef-ad34-1577c1651679
    alterId: 0
    cipher: auto
    tls: true
    skip-cert-verify: true
    servername: sanggorovmess.dwinovasetiana.my.id
    network: ws
    ws-opts:
      path: /hello
      headers:
        Host: sanggorovmess.dwinovasetiana.my.id
    udp: true
  - name: Sggs
    server: 104.26.7.171
    port: 443
    type: vmess
    uuid: dcc2cd00-8ba4-11ef-baa4-1577c1651679
    alterId: 0
    cipher: auto
    tls: true
    skip-cert-verify: true
    servername: 2sggs.dwinovasetiana.my.id
    network: ws
    ws-opts:
      path: /hello
      headers:
        Host: 2sggs.dwinovasetiana.my.id
    udp: true
  - name: Hsp
    server: www.udemy.com
    port: 443
    type: vmess
    uuid: 067dffb0-8ba5-11ef-8ca3-1577c1651679
    alterId: 0
    cipher: auto
    tls: true
    skip-cert-verify: true
    servername: hsp1vmess.dwinovasetiana.my.id.
    network: ws
    ws-opts:
      path: /hello
      headers:
        Host: hsp1vmess.dwinovasetiana.my.id
    udp: true
  - name: Trojan ID Sanggoro
    server: www.udemy.com
    port: 443
    type: trojan
    password: dc3bd980-8ba6-11ef-8974-1577c1651679
    skip-cert-verify: true
    sni: 4lowh.dwinovasetiana.my.id
    network: ws
    ws-opts:
      path: /welcome
      headers:
        Host: 4lowh.dwinovasetiana.my.id
    udp: true
proxy-groups:
  - name: Howdy
    type: select
    proxies:
      - Sanggoro
      - Sggs
      - Hsp
      - Trojan ID Sanggoro
      - balance
      - best-ping
  - name: balance
    type: load-balance
    strategy: consistent-hashing
    url: http://www.gstatic.com/generate_204
    interval: 300
    proxies:
      - Sanggoro
      - Sggs
      - Hsp
      - Trojan ID Sanggoro
  - name: best-ping
    type: url-test
    url: http://www.gstatic.com/generate_204
    interval: 300
    proxies:
      - Sanggoro
      - Sggs
      - Hsp
      - Trojan ID Sanggoro

rules:
  - MATCH,Howdy
